--- 
app: candidate
frameworkVersion: "2"
functions: 
  candidateSubmission: 
    description: "Submit candidate information and starts interview process."
    events: 
      - 
        http: 
          method: POST
          path: candidates
    handler: api/candidate.submit
    memorySize: 128
  users: 
    events: 
      - 
        http: 
          method: post
          path: users/createuser
    handler: api/users.createUser
    memorySize: 128
org: ponokwai
provider: 
  Resource: "*"
  environment: 
    CANDIDATE_EMAIL_TABLE: "candidate-email-${opt:stage, self:provider.stage}"
    CANDIDATE_TABLE: "${self:service}-${opt:stage, self:provider.stage}"
  iamRoleStatements: 
    ? "-Effect"
    : Allow
    Action: 
      - "dynamodb:Query"
      - "dynamodb:Scan"
      - "dynamodb:GetItem"
      - "dynamodb:PutItem"
  lambdaHashingVersion: 20201221
  name: aws
  region: eu-west-1
  runtime: nodejs12.x
  stage: dev
resources: 
  Resources: 
    CandidatesDynamoDbTable: 
      DeletionPolicy: Retain
      Properties: 
        AttributeDefinitions: 
          - 
            AttributeName: id
            AttributeType: S
        KeySchema: 
          - 
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification: 
          StreamViewType: NEW_AND_OLD_IMAGES
        TableName: "${self:provider.environment.CANDIDATE_TABLE}"
      Type: "AWS::DynamoDB::Table"
service: candidate
